# Generated by Django 2.1.4 on 2018-12-22 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0001_initial'),
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Dia'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Horario'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Turno'),
        ),
    ]
