# Generated by Django 2.1.4 on 2018-12-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_auto_20181222_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
